/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { BosonRouterContract } from "./BosonRouter";
import { CashierContract } from "./Cashier";
import { ERC1155ERC721Contract } from "./ERC1155ERC721";
import { ERC1155TokenReceiverContract } from "./ERC1155TokenReceiver";
import { ERC20WithPermitContract } from "./ERC20WithPermit";
import { ERC721TokenReceiverContract } from "./ERC721TokenReceiver";
import { FundLimitsOracleContract } from "./FundLimitsOracle";
import { IBosonRouterContract } from "./IBosonRouter";
import { ICashierContract } from "./ICashier";
import { IERC1155Contract } from "./IERC1155";
import { IERC1155ERC721Contract } from "./IERC1155ERC721";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20WithPermitContract } from "./IERC20WithPermit";
import { IERC721Contract } from "./IERC721";
import { IFundLimitsOracleContract } from "./IFundLimitsOracle";
import { IVoucherKernelContract } from "./IVoucherKernel";
import { MigrationsContract } from "./Migrations";
import { MockERC20PermitContract } from "./MockERC20Permit";
import { OwnableContract } from "./Ownable";
import { PausableContract } from "./Pausable";
import { VoucherKernelContract } from "./VoucherKernel";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "BosonRouter"): BosonRouterContract;
      require(name: "Cashier"): CashierContract;
      require(name: "ERC1155ERC721"): ERC1155ERC721Contract;
      require(name: "ERC1155TokenReceiver"): ERC1155TokenReceiverContract;
      require(name: "ERC20WithPermit"): ERC20WithPermitContract;
      require(name: "ERC721TokenReceiver"): ERC721TokenReceiverContract;
      require(name: "FundLimitsOracle"): FundLimitsOracleContract;
      require(name: "IBosonRouter"): IBosonRouterContract;
      require(name: "ICashier"): ICashierContract;
      require(name: "IERC1155"): IERC1155Contract;
      require(name: "IERC1155ERC721"): IERC1155ERC721Contract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20WithPermit"): IERC20WithPermitContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IFundLimitsOracle"): IFundLimitsOracleContract;
      require(name: "IVoucherKernel"): IVoucherKernelContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "MockERC20Permit"): MockERC20PermitContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "Pausable"): PausableContract;
      require(name: "VoucherKernel"): VoucherKernelContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export { BosonRouterContract, BosonRouterInstance } from "./BosonRouter";
export { CashierContract, CashierInstance } from "./Cashier";
export { ERC1155ERC721Contract, ERC1155ERC721Instance } from "./ERC1155ERC721";
export {
  ERC1155TokenReceiverContract,
  ERC1155TokenReceiverInstance,
} from "./ERC1155TokenReceiver";
export {
  ERC20WithPermitContract,
  ERC20WithPermitInstance,
} from "./ERC20WithPermit";
export {
  ERC721TokenReceiverContract,
  ERC721TokenReceiverInstance,
} from "./ERC721TokenReceiver";
export {
  FundLimitsOracleContract,
  FundLimitsOracleInstance,
} from "./FundLimitsOracle";
export { IBosonRouterContract, IBosonRouterInstance } from "./IBosonRouter";
export { ICashierContract, ICashierInstance } from "./ICashier";
export { IERC1155Contract, IERC1155Instance } from "./IERC1155";
export {
  IERC1155ERC721Contract,
  IERC1155ERC721Instance,
} from "./IERC1155ERC721";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20WithPermitContract,
  IERC20WithPermitInstance,
} from "./IERC20WithPermit";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IFundLimitsOracleContract,
  IFundLimitsOracleInstance,
} from "./IFundLimitsOracle";
export {
  IVoucherKernelContract,
  IVoucherKernelInstance,
} from "./IVoucherKernel";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  MockERC20PermitContract,
  MockERC20PermitInstance,
} from "./MockERC20Permit";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { PausableContract, PausableInstance } from "./Pausable";
export { VoucherKernelContract, VoucherKernelInstance } from "./VoucherKernel";
