/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {}
  }
}
